Document: nacl
Title: Debian nacl Manual
Author: <insert document author here>
Abstract: This manual describes what nacl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nacl/nacl.sgml.gz

Format: postscript
Files: /usr/share/doc/nacl/nacl.ps.gz

Format: text
Files: /usr/share/doc/nacl/nacl.text.gz

Format: HTML
Index: /usr/share/doc/nacl/html/index.html
Files: /usr/share/doc/nacl/html/*.html
